const characters = [{
    name: 'Goku',
    image: 'goku.png',
    health: 200,
    ki: 50,
    maxKi: 200,
    maxHealth: 200,
    canFly: true,
    gravity: 1,
    flyToggleCooldown: 0,
    kiRate: 1,
    grounded: false,
    velocityX: 0,
    velocityY: 1,
    accelerationX: 0,
    accelerationY: 0,
    projectiles: [],
    fists: [], // fists will be initialized during character creation
    currentAttackPower: 0,
    spirit: [0, 0, 200],
    jumpForce: 20,
    shortHopForce: 100,
    costOfFlying: 0.05,
    width: 10,
    height: 10,
    size: 10,
    alive: true,
    friction: 0.9,
    maxSpeed: 5,
    maxJumpDuration: 300,
    jumpKeyPressTime: 0,
    isJumping: false,
    isControllable: true,
    dashSpeed: 200
  },
  {
    name: 'piccolo',
    image: 'piccolo.png',
    health: 200,
    ki: 50,
    maxKi: 200,
    maxHealth: 200,
    canFly: true,
    gravity: 1,
    flyToggleCooldown: 0,
    kiRate: 1,
    grounded: false,
    velocityX: 0,
    velocityY: 1,
    accelerationX: 0,
    accelerationY: 0,
    projectiles: [],
    fists: [], // fists will be initialized during character creation
    currentAttackPower: 0,
    spirit: [0, 250, 0],
    jumpForce: 20,
    shortHopForce: 100,
    costOfFlying: 0.05,
    width: 10,
    height: 10,
    size: 10,
    alive: true,
    friction: 0.9,
    maxSpeed: 5,
    maxJumpDuration: 300,
    jumpKeyPressTime: 0,
    isJumping: false,
    isControllable: true,
    dashSpeed: 200
  },
  {
    name: 'vegeta',
    image: 'vegeta.png',
    health: 200,
    ki: 50,
    maxKi: 200,
    maxHealth: 200,
    canFly: true,
    gravity: 1,
    flyToggleCooldown: 0,
    kiRate: 1,
    grounded: false,
    velocityX: 0,
    velocityY: 1,
    accelerationX: 0,
    accelerationY: 0,
    projectiles: [],
    fists: [], // fists will be initialized during character creation
    currentAttackPower: 0,
    spirit: [200, 0, 200],
    jumpForce: 20,
    shortHopForce: 100,
    costOfFlying: 0.05,
    width: 10,
    height: 10,
    size: 10,
    alive: true,
    friction: 0.9,
    maxSpeed: 5,
    maxJumpDuration: 300,
    jumpKeyPressTime: 0,
    isJumping: false,
    isControllable: true,
    dashSpeed: 200
  },
  {
    name: 'krillin',
    image: 'krillin.png',
    health: 200,
    ki: 50,
    maxKi: 200,
    maxHealth: 200,
    canFly: true,
    gravity: 1,
    flyToggleCooldown: 0,
    kiRate: 1,
    grounded: false,
    velocityX: 0,
    velocityY: 1,
    accelerationX: 0,
    accelerationY: 0,
    projectiles: [],
    fists: [], // fists will be initialized during character creation
    currentAttackPower: 0,
    spirit: [0, 0, 150],
    jumpForce: 20,
    shortHopForce: 100,
    costOfFlying: 0.05,
    width: 10,
    height: 10,
    size: 10,
    alive: true,
    friction: 0.9,
    maxSpeed: 5,
    maxJumpDuration: 300,
    jumpKeyPressTime: 0,
    isJumping: false,
    isControllable: true,
    dashSpeed: 200
  }

];
  

export { characters };